from pages.loginpage import Login
from pages.checkout_page import CheckoutPage
from pages.inventorypage import InventoryPage
from pages.cart_page import CartPage
from utils.user_data_loader import get_user
from utils.pdf_util import PDFUtil
from pathlib import Path


def test_checkout(driver, base_url):
    login = Login(driver)
    checkout_page = CheckoutPage(driver)
    inventory_page = InventoryPage(driver)
    cart_page = CartPage(driver)
    user = get_user()

    driver.get(base_url)
    login.login(user["username"],user["password"])
    inventory_page.apply_sort("Price (low to high)")
    inventory_page.add_cheapest_and_most_expensive()
    inventory_page.driver.find_element(*inventory_page.CART).click()

    assert cart_page.get_cart_item_count() == 2

    cart_page.click_checkout_button()

    assert checkout_page.driver.find_element(*checkout_page.PAGE_TITLE).is_displayed(), "Checkout information page is not displayed"

    checkout_page.enter_checkout_information(
        first_name="Shivam",
        last_name="Sharma",
        postal_code="110001"
    )

    checkout_page.driver.find_element(*checkout_page.CONTINUE_BUTTON).click()

    assert checkout_page.get_page_title() == "Checkout: Overview", (
        "Checkout overview page is not displayed"
    )
    overview_products = checkout_page.get_overview_product_names()
    overview_prices = checkout_page.get_overview_product_prices()

    assert len(overview_products) == 2, (
        f"Expected 2 products, but found {len(overview_products)}"
    )

    assert len(overview_prices) == 2, (
        f"Expected 2 prices, but found {len(overview_prices)}"
    )

    item_total = checkout_page.get_item_total()
    tax = checkout_page.get_tax()
    final_total = checkout_page.get_final_total()

    assert "Item total:" in item_total
    assert "Tax:" in tax
    assert "Total:" in final_total

    checkout_page.click_finish()

    assert checkout_page.get_page_title() == "Checkout: Complete!", (
        "Order confirmation page is not displayed"
    )

    assert "Thank you for your order!" in (
        checkout_page.get_confirmation_text()
        )

    assert "Your order has been dispatched" in (
        checkout_page.get_confirmation_text()
    )

    pdf_path = "order_summary/order_summary.pdf"
    pdf_directory = Path("order_summary")
    pdf_directory.mkdir(exist_ok=True)

    # Remove the previous PDF before starting a new download
    for existing_pdf in pdf_directory.glob("*.pdf"):
        existing_pdf.unlink()

    for partial_file in pdf_directory.glob("*.crdownload"):
        partial_file.unlink()

    # Download the PDF generated by SauceDemo
    checkout_page.download_order_pdf()

    downloaded_pdf = PDFUtil.wait_for_pdf_download(
        download_directory=pdf_directory,
        timeout=20,
    )

    assert downloaded_pdf.exists(), (
        "Order-summary PDF was not downloaded"
    )

    assert downloaded_pdf.stat().st_size > 0, (
        "Downloaded order-summary PDF is empty"
    )

    # Read the downloaded PDF
    pdf_text = PDFUtil.read_pdf(downloaded_pdf)

    # Verify products
    for product_name in overview_products:
        assert product_name in pdf_text, (
            f"Product '{product_name}' is missing from the PDF"
        )

    # Verify product prices
    for product_price in overview_prices:
        assert product_price in pdf_text, (
            f"Price '{product_price}' is missing from the PDF"
        )

    # Verify order amounts
    item_total_amount = item_total.split("$")[-1]
    tax_amount = tax.split("$")[-1]
    final_total_amount = final_total.split("$")[-1]

    item_total_amount = f"${float(item_total_amount):.2f}"
    tax_amount = f"${float(tax_amount):.2f}"
    final_total_amount = f"${float(final_total_amount):.2f}"

    assert item_total_amount in pdf_text
    assert tax_amount in pdf_text
    assert final_total_amount in pdf_text